#  DataSource
spring.datasource.url=jdbc:postgresql://localhost:5432/leaseflow
spring.datasource.username=leaseflow
spring.datasource.password=leaseflow
spring.datasource.driver-class-name=org.postgresql.Driver

#  JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false

#  Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
spring.flyway.baseline-on-migrate=false

#  JWT
jwt.secret=dev-secret-key-change-in-prod-must-be-at-least-256-bits-long-for-hs256
jwt.access-token-expiry-ms=900000
jwt.refresh-token-expiry-ms=604800000

#  Logging
logging.level.com.abm.leaseflow=DEBUG
logging.level.org.springframework.security=DEBUG
logging.level.org.flywaydb=INFO

#  Swagger
springdoc.swagger-ui.enabled=true
springdoc.api-docs.enabled=true
